/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xxhvfhjeytcqesqgpygq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aHZmaGpleXRjcWVzcWdweWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDE4MjUsImV4cCI6MjA3MzcxNzgyNX0.An4c-2uvJZyvqDfp4RckoTAh2ZKW8AXv-_t3F5QLhUk"